<?php
session_start();
require_once 'db.php';

// Check if user is logged in
if (!isset($_SESSION['user_id'])) {
    header('Location: index2.php');
    exit();
}

// Get user details from database
$stmt = $conn->prepare("SELECT first_name, last_name, id_number FROM users WHERE user_id = ?");
$stmt->execute([$_SESSION['user_id']]);
$user = $stmt->fetch(PDO::FETCH_ASSOC);

// If user not found, redirect to login
if (!$user) {
    header('Location: index2.php');
    exit();
}
// Generate a random credit score between 300-850
$creditScore = isset($_SESSION['credit_score']) ? $_SESSION['credit_score'] : rand(300, 850);



// Current date for all timestamps
$currentDate = date('Y-m-d H:i:s');

// Mock credit report data
$creditReport = [
    'credit_score' => $creditScore,
    'negative_listings' => rand(0, 5),
    'active_loans' => rand(0, 3),
    'loan_defaults' => rand(0, 2),
    'report_date' => $currentDate
];
// Generate a random report ID
$reportId = rand(100000, 999999);
// Mock payment data
$payment = [
    'mpesa_code' => 'MPE'.rand(1000000, 9999999),
    'amount' => 50,
    'payment_date' => $currentDate
];
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Your CRB Report</title>
    <style>
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background-color: #f5f7fa;
            margin: 0;
            padding: 0;
            color: #333;
        }
        .rating-modal {
            position: relative;
            max-width: 600px;
            margin: 20px auto;
            background: white;
            border-radius: 12px;
            box-shadow: 0 10px 25px rgba(0, 0, 0, 0.1);
            padding: 25px;
        }
        .rating-close-btn {
            position: absolute;
            top: 15px;
            right: 15px;
            background: none;
            border: none;
            font-size: 24px;
            cursor: pointer;
            color: #999;
        }
        .rating-title {
            font-size: 24px;
            font-weight: 600;
            color: #2c3e50;
            margin-bottom: 5px;
        }
        .rating-subtitle {
            font-size: 14px;
            color: #7f8c8d;
            margin-bottom: 20px;
        }
        .chart-container {
            position: relative;
            width: 200px;
            height: 200px;
            margin: 0 auto 20px;
        }
        .pie-chart {
            width: 100%;
            height: 100%;
        }
        .chart-center {
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            text-align: center;
        }
        .total-score {
            font-size: 36px;
            font-weight: 700;
            color: #2c3e50;
        }
        .score-label {
            font-size: 12px;
            color: #7f8c8d;
            margin-top: -5px;
        }
        .legend {
            display: flex;
            flex-direction: column;
            gap: 8px;
            margin-bottom: 20px;
        }
        .legend-item {
            display: flex;
            align-items: center;
        }
        .legend-color {
            width: 16px;
            height: 16px;
            border-radius: 4px;
            margin-right: 10px;
        }
        .legend-label {
            font-size: 13px;
            color: #2c3e50;
        }
        .legend-value {
            font-size: 12px;
            color: #e74c3c;
            font-weight: 600;
        }
        .rating-status {
            padding: 15px;
            border-radius: 8px;
            margin-bottom: 20px;
        }
        .rating-poor {
            background-color: #fdecea;
            border-left: 4px solid #e74c3c;
        }
        .rating-fair {
            background-color: #fef5e6;
            border-left: 4px solid #f39c12;
        }
        .rating-good {
            background-color: #ebf5fb;
            border-left: 4px solid #3498db;
        }
        .rating-excellent {
            background-color: #e8f8f0;
            border-left: 4px solid #2ecc71;
        }
        h3 {
            margin-top: 0;
        }
    </style>
</head>
<body>
    <div class="rating-modal">
        <button class="rating-close-btn" onclick="window.location.href='index.php'">×</button>
        <div class="rating-title">Your Credit Rating Analysis</div>
        <div class="rating-subtitle">Generated on <?php echo date('F j, Y'); ?></div>
        
        <div class="chart-container">
            <svg class="pie-chart" viewBox="0 0 200 200">
                <!-- Pie chart will be generated by JavaScript -->
            </svg>
            <div class="chart-center">
                <div class="total-score"><?php echo $creditReport['credit_score']; ?></div>
                <div class="score-label">Total Score</div>
            </div>
        </div>

        <div class="legend">
            <div class="legend-item">
                <div class="legend-color" style="background-color: #e74c3c;"></div>
                <div class="legend-text">
                    <div class="legend-label">Poor (200-399)</div>
                    <div class="legend-value"><?php echo $creditReport['credit_score'] < 400 ? 'Your Rating' : ''; ?></div>
                </div>
            </div>
            <div class="legend-item">
                <div class="legend-color" style="background-color: #f39c12;"></div>
                <div class="legend-text">
                    <div class="legend-label">Fair (400-549)</div>
                    <div class="legend-value"><?php echo ($creditReport['credit_score'] >= 400 && $creditReport['credit_score'] < 550) ? 'Your Rating' : ''; ?></div>
                </div>
            </div>
            <div class="legend-item">
                <div class="legend-color" style="background-color: #3498db;"></div>
                <div class="legend-text">
                    <div class="legend-label">Good (550-649)</div>
                    <div class="legend-value"><?php echo ($creditReport['credit_score'] >= 550 && $creditReport['credit_score'] < 650) ? 'Your Rating' : ''; ?></div>
                </div>
            </div>
            <div class="legend-item">
                <div class="legend-color" style="background-color: #9b59b6;"></div>
                <div class="legend-text">
                    <div class="legend-label">Very Good (650-749)</div>
                    <div class="legend-value"><?php echo ($creditReport['credit_score'] >= 650 && $creditReport['credit_score'] < 750) ? 'Your Rating' : ''; ?></div>
                </div>
            </div>
            <div class="legend-item">
                <div class="legend-color" style="background-color: #2ecc71;"></div>
                <div class="legend-text">
                    <div class="legend-label">Excellent (750-850)</div>
                    <div class="legend-value"><?php echo $creditReport['credit_score'] >= 750 ? 'Your Rating' : ''; ?></div>
                </div>
            </div>
        </div>

        <div class="rating-status <?php 
            if ($creditReport['credit_score'] >= 750) echo 'rating-excellent';
            elseif ($creditReport['credit_score'] >= 650) echo 'rating-good';
            elseif ($creditReport['credit_score'] >= 550) echo 'rating-good';
            elseif ($creditReport['credit_score'] >= 400) echo 'rating-fair';
            else echo 'rating-poor';
        ?>">
            <div style="font-size: 1.1em; margin-bottom: 8px;">
                <?php 
                    if ($creditReport['credit_score'] >= 750) echo "EXCELLENT Credit Rating";
                    elseif ($creditReport['credit_score'] >= 650) echo "VERY GOOD Credit Rating";
                    elseif ($creditReport['credit_score'] >= 550) echo "GOOD Credit Rating";
                    elseif ($creditReport['credit_score'] >= 400) echo "FAIR Credit Rating";
                    else echo "POOR Credit Rating";
                ?>
            </div>
            <div style="font-size: 0.9em; opacity: 0.9;">
                <?php 
                    if ($creditReport['credit_score'] >= 750) echo "You qualify for the best loan rates and premium financial products!";
                    elseif ($creditReport['credit_score'] >= 650) echo "You qualify for competitive loan rates and most financial products.";
                    elseif ($creditReport['credit_score'] >= 550) echo "You qualify for standard loan rates with most lenders.";
                    elseif ($creditReport['credit_score'] >= 400) echo "Limited loan options available. Consider improving your credit score.";
                    else echo "Very limited loan options. Focus on improving your payment history.";
                ?>
            </div>
        </div>
        
        <div style="margin-top: 20px; text-align: left; font-size: 0.9em;">
            <h3 style="color: #667eea; margin-bottom: 10px;">Report Details</h3>
            <p><strong>Name:</strong> <?php echo htmlspecialchars($user['first_name']); ?> <?php echo htmlspecialchars($user['last_name']); ?></p>
            <p><strong>Negative Listings:</strong> <?php echo $creditReport['negative_listings']; ?></p>
            <p><strong>Active Loans:</strong> <?php echo $creditReport['active_loans']; ?></p>
            <p><strong>Loan Defaults:</strong> <?php echo $creditReport['loan_defaults']; ?></p>
            <p><strong>Report ID:</strong> CRB-<?php echo str_pad($reportId, 6, '0', STR_PAD_LEFT); ?></p>
            <p><strong>Payment Reference:</strong> <?php echo $payment['mpesa_code']; ?></p>
            <p><strong>Report Date:</strong> <?php echo date('F j, Y', strtotime($creditReport['report_date'])); ?></p>
        </div>
        
        <button style="margin-top: 20px; width: 100%; padding: 12px; background: #667eea; color: white; border: none; border-radius: 8px; cursor: pointer; font-weight: 600;" onclick="window.location.href='index.php'">
            Return to Dashboard
        </button>
        
        <div style="margin-top: 20px; font-size: 12px; color: #95a5a6; text-align: center;">
            <p>This  credit report IS ONLY USED for AGREED purposes only.</p>
            <p>Generated by CRB System</p>
        </div>
    </div>

    <script>
        // Generate pie chart based on credit score
        document.addEventListener('DOMContentLoaded', function() {
            const creditScore = <?php echo $creditReport['credit_score']; ?>;
            const total = 850; // Max possible score
            
            // Calculate percentages for visualization
            const poor = Math.min(399, creditScore) / total * 100;
            const fair = creditScore >= 400 ? Math.min(149, creditScore - 400) / total * 100 : 0;
            const good = creditScore >= 550 ? Math.min(99, creditScore - 550) / total * 100 : 0;
            const veryGood = creditScore >= 650 ? Math.min(99, creditScore - 650) / total * 100 : 0;
            const excellent = creditScore >= 750 ? (creditScore - 750) / total * 100 : 0;
            
            const svg = document.querySelector('.pie-chart');
            const centerX = 100;
            const centerY = 100;
            const radius = 80;
            
            let currentAngle = 0;
            
            function addSlice(angle, color) {
                if (angle <= 0) return;
                
                const startAngle = currentAngle * Math.PI / 180;
                const endAngle = (currentAngle + angle) * Math.PI / 180;
                
                const startX = centerX + radius * Math.cos(startAngle);
                const startY = centerY + radius * Math.sin(startAngle);
                const endX = centerX + radius * Math.cos(endAngle);
                const endY = centerY + radius * Math.sin(endAngle);
                
                const largeArcFlag = angle > 180 ? 1 : 0;
                
                const pathData = [
                    'M', centerX, centerY,
                    'L', startX, startY,
                    'A', radius, radius, 0, largeArcFlag, 1, endX, endY,
                    'Z'
                ].join(' ');
                
                const path = document.createElementNS('http://www.w3.org/2000/svg', 'path');
                path.setAttribute('d', pathData);
                path.setAttribute('fill', color);
                path.setAttribute('class', 'pie-slice');
                
                // Highlight the user's actual rating category
                if ((color === '#e74c3c' && creditScore < 400) ||
                    (color === '#f39c12' && creditScore >= 400 && creditScore < 550) ||
                    (color === '#3498db' && creditScore >= 550 && creditScore < 650) ||
                    (color === '#9b59b6' && creditScore >= 650 && creditScore < 750) ||
                    (color === '#2ecc71' && creditScore >= 750)) {
                    path.style.filter = 'drop-shadow(0 0 8px rgba(0,0,0,0.3))';
                    path.style.strokeWidth = '3';
                    path.style.stroke = '#fff';
                }
                
                svg.appendChild(path);
                currentAngle += angle;
            }
            
            // Add slices in order
            addSlice(poor, '#e74c3c');
            addSlice(fair, '#f39c12');
            addSlice(good, '#3498db');
            addSlice(veryGood, '#9b59b6');
            addSlice(excellent, '#2ecc71');
        });
    </script>
</body>
</html>